/**
 * Deep-sky object photographs from Stellarium's own catalogue
 * (`nebulae/default/textures.json`, 674 entries) — 38 of them here, kept
 * lean against the full ~130MB set, with their credits carried over.
 *
 * Two kinds, and the difference is the whole point. Most are *objects*:
 * under a degree across, invisible until the lens has pulled right in on
 * them. The rest are *fields* — Barnard's Loop is 14° wide, the Cygnus and
 * Cassiopeia complexes 7–9° — and those are what actually give a wide view
 * its texture: the mottled brown-and-dark background a real photo of the
 * Milky Way band has, which no whole-sky panorama at this resolution can
 * supply. A catalogue of nothing but small objects (what this file used to
 * be) can never produce that, however many entries it has.
 *
 * Each carries its own true centre and true angular size, straight from
 * their `worldCoords` quad, so the renderer places and sizes it in real
 * degrees rather than guessing. `maxBrightness` comes from the same
 * catalogue and is Stellarium's own per-image depth cutoff.
 */

export type Nebula = {
  id: string;
  /** File under `public/sky3d/nebulae/`. */
  file: string;
  ne: string;
  en: string;
  /** Messier/NGC/Sharpless designation. */
  catalog: string;
  /** Photographer or observatory, from Stellarium's own catalogue. */
  credit: string;
  /** J2000 right ascension of the image centre, degrees. */
  ra: number;
  /** J2000 declination of the image centre, degrees. */
  dec: number;
  /** True angular width, degrees (already cos(dec)-corrected). */
  widthDeg: number;
  /** True angular height, degrees. */
  heightDeg: number;
  /** Stellarium's own depth cutoff for this image. */
  maxBrightness: number;
};

export const NEBULAE: Nebula[] = [
  {
    id: "barnard_loop_4",
    file: "barnard_loop-4.png",
    ne: "बर्नार्ड लूप",
    en: "Barnard's Loop",
    catalog: "Sh2-276",
    credit: "Sun Shuwei",
    ra: 91.3119,
    dec: 1.3469,
    widthDeg: 14.449,
    heightDeg: 8.5893,
    maxBrightness: 14.2,
  },
  {
    id: "barnard_loop_2",
    file: "barnard_loop-2.png",
    ne: "बर्नार्ड लूप",
    en: "Barnard's Loop",
    catalog: "Sh2-276",
    credit: "Sun Shuwei",
    ra: 81.1885,
    dec: -7.2118,
    widthDeg: 8.7102,
    heightDeg: 8.7466,
    maxBrightness: 14.2,
  },
  {
    id: "barnard_loop_1",
    file: "barnard_loop-1.png",
    ne: "बर्नार्ड लूप",
    en: "Barnard's Loop",
    catalog: "Sh2-276",
    credit: "Sun Shuwei",
    ra: 89.9036,
    dec: -7.25,
    widthDeg: 8.7371,
    heightDeg: 8.676,
    maxBrightness: 14.2,
  },
  {
    id: "sh2_264",
    file: "sh2-264.png",
    ne: "ल्याम्ब्डा ओरायोनिस रिङ",
    en: "Lambda Orionis Ring",
    catalog: "Sh2-264",
    credit: "Wang Lingyi",
    ra: 84.313,
    dec: 9.7476,
    widthDeg: 8.1985,
    heightDeg: 8.1,
    maxBrightness: 14.2,
  },
  {
    id: "dwb111",
    file: "dwb111.png",
    ne: "प्रोपेलर नेब्युला",
    en: "Propeller Nebula",
    catalog: "DWB 111",
    credit: "Giuseppe Donatiello, post-processing: Sun Shuwei",
    ra: 305.4249,
    dec: 44.8517,
    widthDeg: 5.1916,
    heightDeg: 5.2136,
    maxBrightness: 13.5,
  },
  {
    id: "n6960",
    file: "n6960.png",
    ne: "भेल नेब्युला",
    en: "Veil Nebula",
    catalog: "NGC 6960",
    credit: "Jose A Mtanous",
    ra: 313.0254,
    dec: 30.6402,
    widthDeg: 4.9603,
    heightDeg: 4.9554,
    maxBrightness: 13.4,
  },
  {
    id: "n2264",
    file: "n2264.png",
    ne: "क्रिसमस ट्री क्लस्टर",
    en: "Christmas Tree Cluster",
    catalog: "NGC 2264",
    credit: "Giuseppe Donatiello, post-processing: Sun Shuwei",
    ra: 99.7517,
    dec: 9.8065,
    widthDeg: 4.6282,
    heightDeg: 4.7335,
    maxBrightness: 13.6,
  },
  {
    id: "lbn437",
    file: "lbn437.png",
    ne: "ल्याम्ब्डा क्षेत्र",
    en: "Gecko Nebula",
    catalog: "LBN 437",
    credit: "Giuseppe Donatiello, post-processing: Sun Shuwei",
    ra: 338.8869,
    dec: 39.451,
    widthDeg: 4.3759,
    heightDeg: 4.3682,
    maxBrightness: 14.3,
  },
  {
    id: "n7000",
    file: "n7000.png",
    ne: "उत्तर अमेरिका नेब्युला",
    en: "North America Nebula",
    catalog: "NGC 7000",
    credit: "Adam Block/Steward Observatory/University of Arizona",
    ra: 314.0725,
    dec: 44.0165,
    widthDeg: 4.3737,
    heightDeg: 4.3642,
    maxBrightness: 13.2,
  },
  {
    id: "n7822",
    file: "n7822.png",
    ne: "एनजीसी ७८२२",
    en: "NGC 7822",
    catalog: "NGC 7822",
    credit: "Adam Block/Steward Observatory/University of Arizona",
    ra: 0.3192,
    dec: 67.2084,
    widthDeg: 4.2837,
    heightDeg: 4.1502,
    maxBrightness: 14.5,
  },
  {
    id: "barnard_loop_3",
    file: "barnard_loop-3.png",
    ne: "बर्नार्ड लूप",
    en: "Barnard's Loop",
    catalog: "Sh2-276",
    credit: "Sun Shuwei",
    ra: 83.3937,
    dec: 3.0494,
    widthDeg: 4.2832,
    heightDeg: 4.26,
    maxBrightness: 14.2,
  },
  {
    id: "gammacygni_vasey",
    file: "GammaCygni-vasey.png",
    ne: "गामा सिग्नी क्षेत्र",
    en: "Gamma Cygni Region",
    catalog: "IC 1318",
    credit: "Plover Hill Observatory",
    ra: 305.4038,
    dec: 40.1608,
    widthDeg: 3.6034,
    heightDeg: 3.595,
    maxBrightness: 13.4,
  },
  {
    id: "m42",
    file: "m42.png",
    ne: "ओरायन नेब्युला",
    en: "Orion Nebula",
    catalog: "M42",
    credit: "HG731GZ",
    ra: 84.2727,
    dec: -5.726,
    widthDeg: 3.5964,
    heightDeg: 3.5894,
    maxBrightness: 12.5,
  },
  {
    id: "ic1396",
    file: "ic1396.png",
    ne: "एलिफेन्ट ट्रंक",
    en: "Elephant's Trunk",
    catalog: "IC 1396",
    credit: "Giuseppe Donatiello",
    ra: 324.8374,
    dec: 57.4236,
    widthDeg: 3.5663,
    heightDeg: 3.5171,
    maxBrightness: 14.6,
  },
  {
    id: "ic1848",
    file: "ic1848.png",
    ne: "सोल नेब्युला",
    en: "Soul Nebula",
    catalog: "IC 1848",
    credit: "Giuseppe Donatiello, post-processing: Sun Shuwei",
    ra: 44.9301,
    dec: 61.0653,
    widthDeg: 3.3194,
    heightDeg: 3.3067,
    maxBrightness: 14.0,
  },
  {
    id: "ic1805",
    file: "ic1805.png",
    ne: "हर्ट नेब्युला",
    en: "Heart Nebula",
    catalog: "IC 1805",
    credit: "Giuseppe Donatiello, post-processing: Sun Shuwei",
    ra: 38.4907,
    dec: 61.1244,
    widthDeg: 3.2685,
    heightDeg: 3.1956,
    maxBrightness: 14.0,
  },
  {
    id: "etacarinae",
    file: "etaCarinae.png",
    ne: "कारिना नेब्युला",
    en: "Carina Nebula",
    catalog: "NGC 3372",
    credit: "Harel Boren",
    ra: 160.9291,
    dec: -59.8211,
    widthDeg: 3.1016,
    heightDeg: 2.9893,
    maxBrightness: 13.0,
  },
  {
    id: "m31",
    file: "m31.png",
    ne: "एन्ड्रोमेडा ग्यालेक्सी",
    en: "Andromeda Galaxy",
    catalog: "M31",
    credit: "LEE ang HG731GZ",
    ra: 10.7069,
    dec: 41.1598,
    widthDeg: 2.9924,
    heightDeg: 2.9894,
    maxBrightness: 13.5,
  },
  {
    id: "m8",
    file: "m8.png",
    ne: "लगून नेब्युला",
    en: "Lagoon Nebula",
    catalog: "M8",
    credit: "Dylan O'Donnell",
    ra: 271.5359,
    dec: -24.0736,
    widthDeg: 2.5594,
    heightDeg: 2.5579,
    maxBrightness: 13.8,
  },
  {
    id: "pleiades",
    file: "pleiades.png",
    ne: "प्लिएडिज",
    en: "Pleiades",
    catalog: "M45",
    credit: "HG731GZ",
    ra: 56.6601,
    dec: 24.1139,
    widthDeg: 2.1023,
    heightDeg: 2.1021,
    maxBrightness: 12.5,
  },
  {
    id: "m33",
    file: "m33.png",
    ne: "ट्राइएङ्गुलम ग्यालेक्सी",
    en: "Triangulum Galaxy",
    catalog: "M33",
    credit: "HG731GZ",
    ra: 23.4831,
    dec: 30.6601,
    widthDeg: 1.8175,
    heightDeg: 1.8169,
    maxBrightness: 13.4,
  },
  {
    id: "m16",
    file: "m16.png",
    ne: "इगल नेब्युला",
    en: "Eagle Nebula",
    catalog: "M16",
    credit: "Sun Gang",
    ra: 274.7354,
    dec: -13.8064,
    widthDeg: 1.8141,
    heightDeg: 1.8152,
    maxBrightness: 13.6,
  },
  {
    id: "m17",
    file: "m17.png",
    ne: "ओमेगा नेब्युला",
    en: "Omega Nebula",
    catalog: "M17",
    credit: "Dylan O'Donnell",
    ra: 275.1968,
    dec: -16.1241,
    widthDeg: 0.9092,
    heightDeg: 0.9091,
    maxBrightness: 13.4,
  },
  {
    id: "m4",
    file: "m4.png",
    ne: "एम४ क्लस्टर",
    en: "M4 Cluster",
    catalog: "M4",
    credit: "Starhopper",
    ra: 245.9053,
    dec: -26.5335,
    widthDeg: 0.7219,
    heightDeg: 0.7227,
    maxBrightness: 13.6,
  },
  {
    id: "m101_vasey",
    file: "m101-vasey.png",
    ne: "पिनव्हील ग्यालेक्सी",
    en: "Pinwheel Galaxy",
    catalog: "M101",
    credit: "Plover Hill Observatory",
    ra: 210.8587,
    dec: 54.3661,
    widthDeg: 0.6941,
    heightDeg: 0.6889,
    maxBrightness: 13.4,
  },
  {
    id: "m20",
    file: "m20.png",
    ne: "ट्राइफिड नेब्युला",
    en: "Trifid Nebula",
    catalog: "M20",
    credit: "Hewholooks",
    ra: 270.5993,
    dec: -22.9744,
    widthDeg: 0.5573,
    heightDeg: 0.5569,
    maxBrightness: 14.2,
  },
  {
    id: "m81",
    file: "m81.png",
    ne: "बोडेको ग्यालेक्सी",
    en: "Bode's Galaxy",
    catalog: "M81",
    credit: "Kees Scherer, post-processing: Sun Shuwei",
    ra: 148.9001,
    dec: 69.0644,
    widthDeg: 0.4806,
    heightDeg: 0.477,
    maxBrightness: 13.4,
  },
  {
    id: "n7293",
    file: "n7293.png",
    ne: "हेलिक्स नेब्युला",
    en: "Helix Nebula",
    catalog: "NGC 7293",
    credit: "Dylan O'Donnell",
    ra: 337.4005,
    dec: -20.8332,
    widthDeg: 0.4641,
    heightDeg: 0.4634,
    maxBrightness: 13.4,
  },
  {
    id: "m51_vasey",
    file: "m51-vasey.png",
    ne: "वर्लपुल ग्यालेक्सी",
    en: "Whirlpool Galaxy",
    catalog: "M51",
    credit: "Plover Hill Observatory",
    ra: 202.4836,
    dec: 47.2274,
    widthDeg: 0.4543,
    heightDeg: 0.4542,
    maxBrightness: 13.4,
  },
  {
    id: "m13",
    file: "m13.png",
    ne: "हर्क्युलिस क्लस्टर",
    en: "Hercules Cluster",
    catalog: "M13",
    credit: "Starhopper",
    ra: 250.4204,
    dec: 36.4604,
    widthDeg: 0.4496,
    heightDeg: 0.4499,
    maxBrightness: 13.4,
  },
  {
    id: "m22",
    file: "m22.png",
    ne: "सजिटेरियस क्लस्टर",
    en: "Sagittarius Cluster",
    catalog: "M22",
    credit: "Hewholooks",
    ra: 279.1037,
    dec: -23.8983,
    widthDeg: 0.4394,
    heightDeg: 0.4413,
    maxBrightness: 12.8,
  },
  {
    id: "m83",
    file: "m83.png",
    ne: "दक्षिणी पिनव्हील",
    en: "Southern Pinwheel",
    catalog: "M83",
    credit: "TRAPPIST/E. Jehin/ESO",
    ra: 204.2576,
    dec: -29.8705,
    widthDeg: 0.3236,
    heightDeg: 0.3235,
    maxBrightness: 12.8,
  },
  {
    id: "m104",
    file: "m104.png",
    ne: "सोम्ब्रेरो ग्यालेक्सी",
    en: "Sombrero Galaxy",
    catalog: "M104",
    credit: "Adam Block/Mount Lemmon SkyCenter/University of Arizona & Ngc1535, post-processing: Sun Shuwei",
    ra: 189.9968,
    dec: -11.6295,
    widthDeg: 0.2591,
    heightDeg: 0.2587,
    maxBrightness: 12.0,
  },
  {
    id: "m97dumont",
    file: "m97dumont.png",
    ne: "आउल नेब्युला",
    en: "Owl Nebula",
    catalog: "M97",
    credit: "Stephane Dumont",
    ra: 168.706,
    dec: 55.0193,
    widthDeg: 0.252,
    heightDeg: 0.2519,
    maxBrightness: 13.4,
  },
  {
    id: "m11",
    file: "m11.png",
    ne: "वाइल्ड डक क्लस्टर",
    en: "Wild Duck Cluster",
    catalog: "M11",
    credit: "Grasslands Observatory",
    ra: 282.784,
    dec: -6.2653,
    widthDeg: 0.2345,
    heightDeg: 0.2344,
    maxBrightness: 12.2,
  },
  {
    id: "m1dumont",
    file: "m1dumont.png",
    ne: "क्र्याब नेब्युला",
    en: "Crab Nebula",
    catalog: "M1",
    credit: "Stephane Dumont",
    ra: 83.6296,
    dec: 22.0181,
    widthDeg: 0.1457,
    heightDeg: 0.1452,
    maxBrightness: 13.1,
  },
  {
    id: "m27dumont",
    file: "m27dumont.png",
    ne: "डम्बेल नेब्युला",
    en: "Dumbbell Nebula",
    catalog: "M27",
    credit: "Stephane Dumont",
    ra: 299.901,
    dec: 22.7216,
    widthDeg: 0.1421,
    heightDeg: 0.1426,
    maxBrightness: 13.5,
  },
  {
    id: "m57dumont",
    file: "m57dumont.png",
    ne: "रिङ नेब्युला",
    en: "Ring Nebula",
    catalog: "M57",
    credit: "Stephane Dumont",
    ra: 283.3957,
    dec: 33.0281,
    widthDeg: 0.0617,
    heightDeg: 0.062,
    maxBrightness: 12.2,
  },
];

/** `useLoader` needs a stable array of URLs, in the same order every render. */
export const NEBULA_SOURCES: string[] = NEBULAE.map(
  (n) => `${import.meta.env.BASE_URL}sky3d/nebulae/${n.file}`,
);

/* ── flattening ────────────────────────────────────────────────────────── */

import { equatorialToeclipticJ2000 } from "@/lib/sky3d/nakshatra-stars";

export type FlatNebula = {
  nebula: Nebula;
  /** Ecliptic longitude at J2000, degrees. */
  lon: number;
  /** Ecliptic latitude, degrees. */
  lat: number;
  widthRad: number;
  heightRad: number;
  /** The larger of the two angular axes, degrees — what the reveal reads. */
  spanDeg: number;
};

const DEG = Math.PI / 180;

/** {@link NEBULAE}, in the same order as {@link NEBULA_SOURCES}, pre-converted. */
export function flattenNebulae(): FlatNebula[] {
  return NEBULAE.map((nebula) => {
    const { lon, lat } = equatorialToeclipticJ2000(nebula.ra, nebula.dec);
    return {
      nebula,
      lon,
      lat,
      widthRad: nebula.widthDeg * DEG,
      heightRad: nebula.heightDeg * DEG,
      spanDeg: Math.max(nebula.widthDeg, nebula.heightDeg),
    };
  });
}
